# Generated by Django 4.2.21 on 2025-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
