# Generated by Django 4.2.21 on 2025-05-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_client_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
