# Generated by Django 4.2.21 on 2025-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_client_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.TextField(),
        ),
    ]
