# Generated by Django 4.2.21 on 2025-06-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_canva_cctv_flash_hr_java_networking_photoshop_python_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canva',
        ),
        migrations.DeleteModel(
            name='Cctv',
        ),
        migrations.DeleteModel(
            name='Flash',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='Java',
        ),
        migrations.DeleteModel(
            name='Networking',
        ),
        migrations.DeleteModel(
            name='Photoshop',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Sql',
        ),
    ]
