# Generated by Django 4.2.21 on 2025-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_canva_cctv_flash_hr_java_networking_photoshop_python_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pquestion', models.TextField(max_length=500)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
                ('p4', models.CharField(max_length=50)),
                ('pans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Canva',
        ),
        migrations.DeleteModel(
            name='Cctv',
        ),
        migrations.DeleteModel(
            name='Flash',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='Java',
        ),
        migrations.DeleteModel(
            name='Networking',
        ),
        migrations.DeleteModel(
            name='Photoshop',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Sql',
        ),
    ]
