# Generated by Django 4.2.21 on 2025-06-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_pm_delete_canva_delete_cctv_delete_flash_delete_hr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jquestion', models.TextField(max_length=500)),
                ('j1', models.CharField(max_length=50)),
                ('j2', models.CharField(max_length=50)),
                ('j3', models.CharField(max_length=50)),
                ('j4', models.CharField(max_length=50)),
                ('jans', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
