# Generated by Django 4.2.21 on 2025-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_jm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photoshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
