# Generated by Django 4.2.21 on 2025-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_canva_cctv_flash_hr_networking_photoshop_router_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
