# Generated by Django 4.2.21 on 2025-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tech_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='topic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
