# Generated by Django 4.2.21 on 2025-06-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_client_tech_score_client_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jm',
            old_name='jans',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='jm',
            old_name='j1',
            new_name='o1',
        ),
        migrations.RenameField(
            model_name='jm',
            old_name='j2',
            new_name='o2',
        ),
        migrations.RenameField(
            model_name='jm',
            old_name='j3',
            new_name='o3',
        ),
        migrations.RenameField(
            model_name='jm',
            old_name='j4',
            new_name='o4',
        ),
        migrations.RenameField(
            model_name='jm',
            old_name='jquestion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='pans',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='p1',
            new_name='o1',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='p2',
            new_name='o2',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='p3',
            new_name='o3',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='p4',
            new_name='o4',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='pquestion',
            new_name='question',
        ),
    ]
