# Generated by Django 4.2.21 on 2025-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_rename_jans_jm_ans_rename_j1_jm_o1_rename_j2_jm_o2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
