# Generated by Django 4.2.21 on 2025-06-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_client_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('a1', models.CharField(max_length=100)),
                ('s1', models.CharField(max_length=100)),
                ('q2', models.TextField()),
                ('a2', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
                ('q3', models.TextField()),
                ('a3', models.CharField(max_length=100)),
                ('s3', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.client')),
            ],
        ),
    ]
