# Generated by Django 4.2.21 on 2025-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='a1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='a2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='a3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='q2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='q3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='s1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='s2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='s3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
