# Generated by Django 4.2.21 on 2025-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_alter_output_a1_alter_output_a2_alter_output_a3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='output',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='output',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='output',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='output',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='output',
            name='s3',
        ),
    ]
