# Generated by Django 4.2.21 on 2025-06-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_remove_output_a2_remove_output_a3_remove_output_q2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Output',
        ),
    ]
