# Generated by Django 5.2.3 on 2025-06-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_emp_delete_client_alter_result_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
