# Generated by Django 5.2.3 on 2025-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='total_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
