# Generated by Django 5.2.3 on 2025-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_alter_emp_total_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='current_employer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='year_of_graduation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
