# Generated by Django 5.2.3 on 2025-07-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_alter_emp_current_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='highest_qualification',
            new_name='basic_qualification',
        ),
        migrations.AddField(
            model_name='emp',
            name='pg_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='pg_degree_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='pg_passed_out',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
